# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cookbooks
tagline:          Text recepies for building linux servers on the cloud 
url:              http://antespi.github.io/cookbooks
paginate:         1
baseurl:          /
author:
  name:           Antonio Espinosa
  url:            https://twitter.com/antespi
  email:          antespi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/antespi/cookbooks
